version: "3"
services:
  api_service:
    build: .
    image: desafio-dev
    restart: always
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/mysql_database?allowPublicKeyRetrieval=true&useSSL=False
    networks:
      - projeto_network
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - projeto_network
    environment:
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: user_bycoders
      MYSQL_PASSWORD: projeto123
      MYSQL_ROOT_PASSWORD: root123
networks:
  projeto_network: 